language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install

script:
  - echo $(phpenv version-name)
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-9.5.4.phar
  - phpunit --version
  - phpunit --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
